server:
    port: ${PORT:8000}
    max-http-header-size:
      16KB

spring:
  http:
    multipart:
      enabled: false

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB